TARGET_VENUES = (
    "CVPR",
    "ICCV",
    "ECCV",
    "ICLR",
    "NEURIPS",
    "ICML",
    "AAAI",
    "IEEE TPAMI",
    "TPAMI",
)

VENUE_ALIASES = {
    "conference on computer vision and pattern recognition": "CVPR",
    "international conference on computer vision": "ICCV",
    "european conference on computer vision": "ECCV",
    "international conference on learning representations": "ICLR",
    "advances in neural information processing systems": "NeurIPS",
    "neural information processing systems": "NeurIPS",
    "neurips": "NeurIPS",
    "nips": "NeurIPS",
    "international conference on machine learning": "ICML",
    "aaai conference on artificial intelligence": "AAAI",
    "ieee transactions on pattern analysis and machine intelligence": "IEEE TPAMI",
    "transactions on pattern analysis and machine intelligence": "IEEE TPAMI",
    "tpami": "IEEE TPAMI",
}

VLM_KEYWORDS = (
    "vision-language",
    "vision language",
    "visual-language",
    "visual language",
    "multimodal large language model",
    "multi-modal large language model",
    "multimodal llm",
    "multi-modal llm",
    "large multimodal model",
    "large multi-modal model",
    "vlm",
    "vllm",
    "image-text",
    "image text",
    "video-text",
    "video text",
    "visual question answering",
    "vqa",
    "document vqa",
    "visual grounding",
    "referring expression",
    "image captioning",
    "video captioning",
    "text-to-image",
    "text to image",
    "vision instruction",
)

CODE_URL_PATTERNS = (
    "github.com",
    "gitlab.com",
    "bitbucket.org",
    "huggingface.co",
    "paperswithcode.com",
)
